CREATE TABLE ROOT.FR_FACILITIESINFO (
	ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(100),
	FACILITIESTYPEID INTEGER,
	PRIMARY KEY (ID)
);
CREATE TABLE ROOT.FR_FACILITIESTYPE (
	ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(100),
	PRIMARY KEY (ID)
);
CREATE TABLE ROOT.FR_FUNCTION (
	ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(100),
	URL VARCHAR(500),
	PRIMARY KEY (ID)
);
CREATE TABLE ROOT.FR_FUNCTION_USER (
	FUNCTIONID INTEGER,
	USERID INTEGER
);
CREATE TABLE ROOT.FR_GRADE (
	ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(100),
	PRIMARY KEY (ID)
);
CREATE TABLE ROOT.FR_RESERVERECORD (
	ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	FACILITYID INTEGER,
	STARTDATE VARCHAR(100),
	ENDDATE VARCHAR(100),
	USERID INTEGER,
	CREATEDATE VARCHAR(100),
	USERNAME VARCHAR(100),
	ISABSENCE INTEGER,
	FACILITYNAME VARCHAR(100),
	PRIMARY KEY (ID)
);
CREATE TABLE ROOT.FR_USER (
	ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ACCOUNT VARCHAR(100),
	NAME VARCHAR(100),
	PASSWORD VARCHAR(100),
	GRADEID INTEGER,
	USERTYPEID INTEGER,
	ISVALID INTEGER,
	ABSENCENUM INTEGER,
	ABSENCEDATE VARCHAR(100),
	CREATEDATE VARCHAR(100),
	PRIMARY KEY (ID)
);
CREATE TABLE ROOT.FR_USERTYPE (
	ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(100),
	PRIMARY KEY (ID)
);
CREATE TABLE ROOT.FR_VACATION (
	ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(100),
	STARTDATE VARCHAR(100),
	ENDDATE VARCHAR(100),
	PRIMARY KEY (ID)
);
INSERT INTO ROOT.FR_FACILITIESINFO(NAME, FACILITIESTYPEID) VALUES ('篮球', 1);
INSERT INTO ROOT.FR_FACILITIESINFO(NAME, FACILITIESTYPEID) VALUES ('羽毛球拍', 2);
INSERT INTO ROOT.FR_FACILITIESINFO(NAME, FACILITIESTYPEID) VALUES ('乒乓球拍', 3);
INSERT INTO ROOT.FR_FACILITIESTYPE(NAME) VALUES ('篮球室');
INSERT INTO ROOT.FR_FACILITIESTYPE(NAME) VALUES ('羽毛球室');
INSERT INTO ROOT.FR_FACILITIESTYPE(NAME) VALUES ('乒乓球室');
INSERT INTO ROOT.FR_FUNCTION(NAME, URL) VALUES ('人员管理', 'userManager.do');
INSERT INTO ROOT.FR_FUNCTION(NAME, URL) VALUES ('设备管理', 'facilitiesManager.do');
INSERT INTO ROOT.FR_FUNCTION(NAME, URL) VALUES ('预约管理', 'reserveManager.do');
INSERT INTO ROOT.FR_FUNCTION(NAME, URL) VALUES ('假期管理', 'vacationManager.do');
INSERT INTO ROOT.FR_FUNCTION(NAME, URL) VALUES ('班级管理', 'gradeManager.do');
INSERT INTO ROOT.FR_FUNCTION(NAME, URL) VALUES ('设备使用统计', 'facilitiesReport.do');
INSERT INTO ROOT.FR_FUNCTION(NAME, URL) VALUES ('预约查询', 'reserveFind.do');
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (1, 1);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (2, 1);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (3, 1);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (4, 1);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (5, 1);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (6, 1);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (7, 1);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (3, 2);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (7, 2);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (3, 3);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (7, 3);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (3, 4);
INSERT INTO ROOT.FR_FUNCTION_USER(FUNCTIONID, USERID) VALUES (1, 2);
INSERT INTO ROOT.FR_GRADE(NAME) VALUES ('1301班级');
INSERT INTO ROOT.FR_GRADE(NAME) VALUES ('1302班级');
INSERT INTO ROOT.FR_GRADE(NAME) VALUES ('1303班级');
INSERT INTO ROOT.FR_USER(ACCOUNT, NAME, PASSWORD, GRADEID, USERTYPEID, ISVALID, ABSENCENUM, ABSENCEDATE, CREATEDATE) VALUES ('admin', '管理员', 'admin', 0, 1, 1, 0, null, null);
INSERT INTO ROOT.FR_USERTYPE(NAME) VALUES ('管理员');
INSERT INTO ROOT.FR_USERTYPE(NAME) VALUES ('操作员');
INSERT INTO ROOT.FR_USERTYPE(NAME) VALUES ('教师');
INSERT INTO ROOT.FR_USERTYPE(NAME) VALUES ('学生');
INSERT INTO ROOT.FR_VACATION(NAME, STARTDATE, ENDDATE) VALUES ('十月一国庆', '2013-10-01', '2013-10-07');